### ISSUE TITLE
pfsense 2.7 working?

### ISSUE THREAD

**Issue by alexw1982** [unofficial-unifi/unifi-pfsense#320]
I tried to upgrade to 2.7 yesterday but ran into issues. Running the installer script did not help either.

anybody else experienced this or had success installing unifi?

**Comment by tong2x** [comment]
any details you can share?
what errors did you see or record?
clean install?
which script did you run?

**Comment by salinbraga** [comment]
When I went to install it, it gave an error, the installation is clean.
follows the error:

fetch -o - https://tin                                                                                                             yurl.com/3ukj9253 | sh -s
-                                                     8769  B   45 MBps    00s
sh: mongod: not found
Adding fdesc filesystem to /etc/fstab... done.
Adding procfs filesystem to /etc/fstab... done.
Mounting new filesystems... done.
Gathering package list from remote repository...
Done.
Removing discontinued packages...
 done.
Installing required packages...
Fetching png-1.6.39.pkg: 100%  306 KiB 313.7kB/s    00:01
Installing png-1.6.39...
Extracting png-1.6.39: 100%
Fetching brotli-1.0.9,1.pkg: 100%  397 KiB 406.7kB/s    00:01
Installing brotli-1.0.9,1...
Extracting brotli-1.0.9,1: 100%
Fetching freetype2-2.12.1_2.pkg: 100%    1 MiB 556.9kB/s    00:02
Installing freetype2-2.12.1_2...
Extracting freetype2-2.12.1_2: 100%
=====
Message from freetype2-2.12.1_2:

--
The 2.7.x series now uses the new subpixel hinting mode (V40 port's option) as
the default, emulating a modern version of ClearType. This change inevitably
leads to different rendering results, and you might change port's options to
adapt it to your taste (or use the new "FREETYPE_PROPERTIES" environment
variable).

The environment variable "FREETYPE_PROPERTIES" can be used to control the
driver properties. Example:

FREETYPE_PROPERTIES=truetype:interpreter-version=35 \
        cff:no-stem-darkening=1 \
        autofitter:warping=1

This allows to select, say, the subpixel hinting mode at runtime for a given
application.

If LONG_PCF_NAMES port's option was enabled, the PCF family names may include
the foundry and information whether they contain wide characters. For example,
"Sony Fixed" or "Misc Fixed Wide", instead of "Fixed". This can be disabled at
run time with using pcf:no-long-family-names property, if needed. Example:

FREETYPE_PROPERTIES=pcf:no-long-family-names=1

How to recreate fontconfig cache with using such environment variable,
if needed:
# env FREETYPE_PROPERTIES=pcf:no-long-family-names=1 fc-cache -fsv

The controllable properties are listed in the section "Controlling FreeType
Modules" in the reference's table of contents
(/usr/local/share/doc/freetype2/reference/index.html, if documentation was insta                                                                                                             lled).
Fetching fontconfig-2.14.2,1.pkg: 100%  493 KiB 505.2kB/s    00:01
Installing fontconfig-2.14.2,1...
Extracting fontconfig-2.14.2,1: 100%
Running fc-cache to build fontconfig cache...
Fetching alsa-lib-1.2.2_1.pkg: 100%  473 KiB 484.8kB/s    00:01
Installing alsa-lib-1.2.2_1...
Extracting alsa-lib-1.2.2_1: 100%
=====
Message from alsa-lib-1.2.2_1:

--
===>   NOTICE:

The alsa-lib port currently does not have a maintainer. As a result, it is
more likely to have unresolved issues, not be up-to-date, or even be removed in
the future. To volunteer to maintain this port, please create an issue at:

https://bugs.freebsd.org/bugzilla

More information about port maintainership is available at:

https://docs.freebsd.org/en/articles/contributing/#ports-contributing
Package mpdecimal-2.5.1 already installed.
Fetching : 100%    2 KiB   2.3kB/s    00:01
pkg: archive_read_open_filename(/tmp/.XXXXX): Unrecognized archive format

Failed to install the following 1 package(s): https://pkg.freebsd.org/FreeBSD:14                                                                                                             :amd64/latest/

**Comment by tong2x** [comment]
try 
Install command: fetch -o - https://tinyurl.com/edfwfc5y | sh -s
but since this is FreeBsd14, this may be a major change in the packages.
just like from freebsd12 to freebsd13

**Comment by salinbraga** [comment]
It wasn't either, it gave another error, I believe there was a big change with version 2.7.0
Here's the error:

fetch -o - https://tinyurl.com/edfwfc5y | sh -s
-                                                     8870  B   44 MBps    00s
sh: mongod: not found
Mounting new filesystems... done.
Gathering package list from remote repository...
Done.
Removing discontinued packages...
 done.
Installing required packages...
Package png-1.6.39 already installed.
Package brotli-1.0.9,1 already installed.
Fetching jpeg-turbo-2.1.5.1.pkg: 100%  382 KiB 391.3kB/s    00:01
Installing jpeg-turbo-2.1.5.1...
Extracting jpeg-turbo-2.1.5.1: 100%
Fetching zstd-1.5.5.pkg: 100%  547 KiB 560.3kB/s    00:01
Installing zstd-1.5.5...
package zstd is already installed, forced install
Extracting zstd-1.5.5: 100%
Fetching libdeflate-1.18.pkg: 100%   77 KiB  79.1kB/s    00:01
Installing libdeflate-1.18...
Extracting libdeflate-1.18: 100%
Fetching jbigkit-2.1_1.pkg: 100%   78 KiB  79.6kB/s    00:01
Installing jbigkit-2.1_1...
Extracting jbigkit-2.1_1: 100%
Fetching tiff-4.4.0_1.pkg: 100%  896 KiB 917.2kB/s    00:01
Installing tiff-4.4.0_1...
Extracting tiff-4.4.0_1: 100%
Package freetype2-2.12.1_2 already installed.
Package fontconfig-2.14.2,1 already installed.
Package alsa-lib-1.2.2_1 already installed.
Package mpdecimal-2.5.1 already installed.
Fetching : 100%    2 KiB   2.3kB/s    00:01
pkg: archive_read_open_filename(/tmp/.XXXXX): Unrecognized archive format

Failed to install the following 1 package(s): https://pkg.freebsd.org/FreeBSD:14:amd64/latest/
[2.7.0-RELEASE][admin@bacabal.grupomarilia.local]/root: pkg update
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
All repositories are up to date.

**Comment by tong2x** [comment]
it would seem the major part mongodb 4 is missing or update in freebsd14
lets wait for now for the other team to check the script and update package version/name

**Comment by dvdp** [comment]
So far, I only found mongo70 for freebsd14
I managed to get it installed by adding
AddPkg snowballstemmer
AddPkg yaml-cpp
AddPkg mongodb70
But I can't get it to run:
ld-elf.so.1: Shared object "libcrypto.so.30" not found, required by "mongod"
I tried to fix that by AddPkg openssl30 but no luck ... and I doubt that the UniFi stuff will work with that mongodb 7.0

**Comment by DirectXMan12** [comment]
ok so, based on some digging, it looks like FreeBSD 4.0 switched to OpenSSL 3.0, but merged that commit *after* pfsense 7.2.  Thus, we're hitting the issue of "latest packages built for FreeBSD:xyx:14 base expect OpenSSL 3.0, but we (pfsense) haven't quite caught up to that base yet" (at least, with the `libssl.so.30` error, which is what I'm seeing as of today)

Good news is that based on https://github.com/pfsense/FreeBSD-src/commit/b077aed33b7b6aefca7b17ddb250cf521f938613, we're gonna be getting OpenSSL *eventually* and all will be back to normal and good (in theory).

Other good news is that it *looks* like FreeBSD:xyz:13's build of mongodb44 works just fine on pfsense 7.2.  I'm gonna test that, but might be a workaround if you don't wanna switch to pfsense development.  I'll update this with what I find

**Comment by DirectXMan12** [comment]
manually switching to FreeBSD 13's mongodb44 worked fine. my script is hacky rn, but if you want i'm willing to PR in something more robust as an option.  not sure what they best way to detect this is if we want to though -- maybe look at pfsense version?

**Comment by tong2x** [comment]
yes please lets see something just a a workaround for the moment

**Comment by dvdp** [comment]
Looks like this might get fixed in the near future:
https://docs.netgate.com/pfsense/en/latest/releases/23-09.html
which says:
...
OpenSSL in the base system has been upgraded from 1.1.1t to 3.0.12.
...
Question remains: when will it get ported to pfSense CE ...
