### ISSUE TITLE
HTTP Status 404 – Not Found - PF 2.7

### ISSUE THREAD

**Issue by namdoan91** [unofficial-unifi/unifi-pfsense#324]
I am using pfSense 2.7, installed Unifi version 7.5.165, and completed the installation. However, when I access the web, it shows an error 'HTTP Status 404 – Not Found".' Is there any way to fix this? I followed the instructions from this link: https://raw.githubusercontent.com/unofficial-unifi/unifi-pfsense/429635cfcd980c11c53d9586f94bd4bf4505b6dc/install-unifi/install-unifi.sh

**Comment by tong2x** [comment]
this is the trial mongodb 44, hmmmm improvement vs the errors.
please waiting for some time and or restarting pfsense
you can also try killing the PID and starting unifi

**Comment by fabriciocampos2022** [comment]
the neweste pfsense use Freebsd14 and have some problem to installl with the original script.
the problem is with python 37 and 38 and mongodb.

To solve this problem I used the script from: https://github.com/DirectXMan12/unifi-pfsense/blob/3dcf6016f8c318ea4c4115aabe6395a43fd8e807/install-unifi/install-unifi.sh

but, need change the line 38 from this script...
=====================   original script
# FreeBSD package source:
FREEBSD_PACKAGE_URL="https://pkg.freebsd.org/${ABI}/latest/"
=============== new config
FREEBSD_PACKAGE_URL="https://pkg.freebsd.org/FreeBSD:14:amd64/latest/"


and line 116
=========== original script
base_url=${2:-FREEBSD_PACKAGE_URL}

=================new config
 base_url=${2:-$FREEBSD_PACKAGE_URL}

**Comment by sikysikov** [comment]
So changing the script in your link succesfully installed UNIFI and is working? Now 404 error?

**Comment by sikysikov** [comment]
@tong2x I am still getting following error while installing latest beta on pfSense 2.7:

ld-elf.so.1: Shared object "libcrypto.so.30" not found, required by "mongod"

**Comment by tong2x** [comment]
related to 
#324
#320 
something about "libcrypto.so.30" being of different version ang unfortunately not compatible with mondodb in PFsense 2.7
